[package]
name = "rust"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[dependencies]
jni = { version = "0.19.0", default-features = false }
android_logger = "0.11"
log = { workspace = true }
zingoappshim = { workspace = true }

[lib]
crate-type = ["dylib"]
