[workspace]
members = [
    "android",
    "ios"
]

[workspace.dependencies]
log = "0.4.8"
zingoappshim = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "dev" }

[profile.release]
debug = false
