[workspace]
members = [
    "android",
    "ios"
]

[workspace.dependencies]
log = "0.4.8"
zingoappshim = { git="https://github.com/zancas/zingolib", default-features=true, branch = "add_app_shim" }

[profile.release]
debug = false

[patch.crates-io]
zcash_note_encryption = { git = "https://github.com/zingolabs/librustzcash", rev = "acfdabc3629c93517e3c4742848996c595de6d3c" }
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash", rev = "acfdabc3629c93517e3c4742848996c595de6d3c" }
