[package]
name = "rustios"
version = "1.0.1"
authors = ["Zingolabs <zingo@zingolabs.com>"]
edition = "2021"

[dependencies]
log = { workspace = true }
rustappshim = { workspace = true }

[lib]
name = "rustios"
crate-type = ["staticlib"]
