name: buildndk

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: build ndk
        uses: actions/checkout@v3
      - run:  cd rust && ./build.sh

  yarn_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Yarn
      uses: docker://node:latest
    - run: yarn install
    - run: yarn test